steps:
  - name: node
    entrypoint: npm
    args: ['install']

  - name: bash
    args:
      - '-c'
      - |
          echo {"GCLOUD_PROJECT":"$PROJECT_ID"} > config.json

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]

timeout: "1600s"